From b0a3b43381939694368bfaaf00808804c711b99b Mon Sep 17 00:00:00 2001
From: Yaroslav Halchenko <debian@onerussian.com>
Date: Thu, 26 Jul 2018 10:59:52 -0400
Subject: [PATCH] BF: Define "message" since exception might happen in initial
 import

---
 sklearn/tests/test_init.py | 1 +
 1 file changed, 1 insertion(+)

diff --git a/sklearn/tests/test_init.py b/sklearn/tests/test_init.py
index 17b78632f..eef57578d 100644
--- a/sklearn/tests/test_init.py
+++ b/sklearn/tests/test_init.py
@@ -28,6 +28,7 @@ def test_import_skl():
 def test_import_sklearn_no_warnings():
     # Test that importing scikit-learn main modules doesn't raise any warnings.
 
+    message = "No message yet"
     try:
         pkgs = pkgutil.iter_modules(path=sklearn.__path__, prefix='sklearn.')
         import_modules = '; '.join(['import ' + modname
-- 
2.18.0

